#pragma once
#include <graphics.h>
#include "common_def.h"
static int map[MAP_CNT] =
{
	WALL,WALL,WALL,WALL,WALL, WALL,WALL,WALL,WALL,WALL, WALL, WALL,WALL,WALL,WALL,WALL, WALL,WALL,WALL,WALL,WALL,
	WALL,BEAN,BEAN,BEAN,BEAN, BEAN,BEAN,BEAN,BEAN,BEAN, WALL, BEAN,BEAN,BEAN,BEAN,BEAN, BEAN,BEAN,BEAN,BEAN,WALL,
	WALL,BEAN,WALL,WALL,WALL, BEAN,WALL,WALL,WALL,BEAN, WALL, BEAN,WALL,WALL,WALL,BEAN, WALL,WALL,WALL,BEAN,WALL,
	WALL,BEAN,WALL,NULL,WALL, BEAN,WALL,NULL,WALL,BEAN, WALL, BEAN,WALL,NULL,WALL,BEAN, WALL,NULL,WALL,BEAN,WALL,
	WALL,BEAN,WALL,WALL,WALL, BEAN,WALL,WALL,WALL,BEAN, WALL, BEAN,WALL,WALL,WALL,BEAN, WALL,WALL,WALL,BEAN,WALL,

	WALL,BIGB,BEAN,BEAN,BEAN, BEAN,BEAN,BEAN,BEAN,BEAN, BEAN, BEAN,BEAN,BEAN,BEAN,BEAN, BEAN,BEAN,BEAN,BIGB,WALL,
	WALL,BEAN,WALL,WALL,WALL, BEAN,WALL,BEAN,WALL,WALL, WALL, WALL,WALL,BEAN,WALL,BEAN, WALL,WALL,WALL,BEAN,WALL,
	WALL,BEAN,WALL,WALL,WALL, BEAN,WALL,BEAN,WALL,WALL, WALL, WALL,WALL,BEAN,WALL,BEAN, WALL,WALL,WALL,BEAN,WALL,
	WALL,BEAN,BEAN,BEAN,BEAN, BEAN,WALL,BEAN,BEAN,BEAN, WALL, BEAN,BEAN,BEAN,WALL,BEAN, BEAN,BEAN,BEAN,BEAN,WALL,
	WALL,WALL,WALL,WALL,WALL, BEAN,WALL,WALL,WALL,BEAN, WALL, BEAN,WALL,WALL,WALL,BEAN, WALL,WALL,WALL,WALL,WALL,

	NULL,NULL,NULL,NULL,WALL, BEAN,WALL,NULL,NULL,NULL, NULL, NULL,NULL,NULL,WALL,BEAN, WALL,NULL,NULL,NULL,NULL,
	NULL,NULL,NULL,NULL,WALL, BEAN,WALL,NULL,WALL,WALL, NULL, WALL,WALL,NULL,WALL,BEAN, WALL,NULL,NULL,NULL,NULL,
	WALL,WALL,WALL,WALL,WALL, BEAN,WALL,NULL,WALL,NULL, NULL, NULL,WALL,NULL,WALL,BEAN, WALL,WALL,WALL,WALL,WALL,
	NULL,NULL,NULL,NULL,NULL, BEAN,NULL,NULL,WALL,NULL, NULL, NULL,WALL,NULL,NULL,BEAN, NULL,NULL,NULL,NULL,NULL,
	WALL,WALL,WALL,WALL,WALL, BEAN,WALL,NULL,WALL,WALL, WALL, WALL,WALL,NULL,WALL,BEAN, WALL,WALL,WALL,WALL,WALL,

	NULL,NULL,NULL,NULL,WALL, BEAN,WALL,NULL,NULL,NULL, NULL, NULL,NULL,NULL,WALL,BEAN, WALL,NULL,NULL,NULL,NULL,
	NULL,NULL,NULL,NULL,WALL, BEAN,WALL,NULL,WALL,WALL, WALL, WALL,WALL,NULL,WALL,BEAN, WALL,NULL,NULL,NULL,NULL,
	WALL,WALL,WALL,WALL,WALL, BEAN,WALL,NULL,WALL,WALL, WALL, WALL,WALL,NULL,WALL,BEAN, WALL,WALL,WALL,WALL,WALL,
	WALL,BEAN,BEAN,BEAN,BEAN, BEAN,BEAN,BEAN,BEAN,BEAN, WALL, BEAN,BEAN,BEAN,BEAN,BEAN, BEAN,BEAN,BEAN,BEAN,WALL,
	WALL,BEAN,WALL,WALL,WALL, BEAN,WALL,WALL,WALL,BEAN, WALL, BEAN,WALL,WALL,WALL,BEAN, WALL,WALL,WALL,BEAN,WALL,

	WALL,BIGB,BEAN,BEAN,WALL, BEAN,BEAN,BEAN,BEAN,BEAN, BEAN, BEAN,BEAN,BEAN,BEAN,BEAN, WALL,BEAN,BEAN,BIGB,WALL,
	WALL,WALL,WALL,BEAN,WALL, BEAN,WALL,BEAN,WALL,WALL, WALL, WALL,WALL,BEAN,WALL,BEAN, WALL,BEAN,WALL,WALL,WALL,
	WALL,WALL,WALL,BEAN,WALL, BEAN,WALL,BEAN,WALL,WALL, WALL, WALL,WALL,BEAN,WALL,BEAN, WALL,BEAN,WALL,WALL,WALL,
	WALL,BEAN,BEAN,BEAN,BEAN, BEAN,WALL,BEAN,BEAN,BEAN, WALL, BEAN,BEAN,BEAN,WALL,BEAN, BEAN,BEAN,BEAN,BEAN,WALL,
	WALL,BEAN,WALL,WALL,WALL, WALL,WALL,WALL,WALL,BEAN, WALL, BEAN,WALL,WALL,WALL,WALL, WALL,WALL,WALL,BEAN,WALL,

	WALL,BEAN,BEAN,BEAN,BEAN, BEAN,BEAN,BEAN,BEAN,BEAN, BEAN, BEAN,BEAN,BEAN,BEAN,BEAN, BEAN,BEAN,BEAN,BEAN,WALL,
	WALL,WALL,WALL,WALL,WALL, WALL,WALL,WALL,WALL,WALL, WALL, WALL,WALL,WALL,WALL,WALL, WALL,WALL,WALL,WALL,WALL,
};

class CBackground
{
public:
	CBackground();
	CBackground(const LPCTSTR sFile);
	void SetFile(const LPCTSTR sFile);
	IMAGE* GetBG();
	IMAGE* GetBGWBEAN();
	void Paint();
	bool isWall(int nX, int nY);
private:
	LPCTSTR m_sFile;
	IMAGE IMBackground;
	IMAGE IMBackgroundWithBEAN;
};