GetPeData proto
GetDosStructAddr proto
GetNtStructAddr proto
GetFileHStructAddr proto
GetOptionalStructAddr proto
GetDataDirStructAddr proto
GetSectionHeadersAddr proto
GetImportDirectoryAddr proto
GetDataDirStructLen proto
GetSectionHeadersLen proto
GetImportDirectoryLen proto
GetRVAtoFA proto dwRva:DWORD
GetRVAtoVA proto dwRva:DWORD
GetFAtoRVA proto dwFa:DWORD
GetFAtoVA proto dwFa:DWORD
GetVAtoRVA proto dwVa:DWORD
GetVAtoFA proto dwVa:DWORD
ClearPeData proto